### ISSUE TITLE
H2190 Scone Model location

### ISSUE THREAD

**Issue by YusseffRuiz** [martius-lab/depRL#10]
Is there any location where i can find the H2190 musculoskeletal body? 
I'm planning to use it and reference it in a reseach for scone usage and comparison with other simulation tools.
Can you help me?

**Comment by P-Schumacher** [comment]
Hi!
The scone/hyfydy models are available here:
https://github.com/tgeijten/sconegym/tree/main/sconegym/data-v1

but might require a hyfydy license. You can request a trial license on: hyfydy.com
